param(
  [Parameter(Mandatory = $true)]
  [string]$BatchName,
  [string]$Date = (Get-Date).ToString("yyyyMMdd")
)

$ErrorActionPreference = "Stop"

function Normalize-Topic([string]$text) {
  $v = $text.Trim().ToLowerInvariant()
  $v = [regex]::Replace($v, "[^a-z0-9]+", "-")
  $v = [regex]::Replace($v, "-{2,}", "-")
  $v = $v.Trim("-")
  if ([string]::IsNullOrWhiteSpace($v)) {
    throw "BatchName must contain at least one letter or digit."
  }
  return $v
}

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $repoRoot
$seedDir = Join-Path $repoRoot "db\seed"

if (!(Test-Path $seedDir)) {
  throw "Seed directory not found: $seedDir"
}

$topic = Normalize-Topic $BatchName
$existing = Get-ChildItem -Path $seedDir -Filter "*.sql" -File
$maxNo = 0

foreach ($f in $existing) {
  if ($f.Name -match "^([0-9]{3})_") {
    $n = [int]$matches[1]
    if ($n -gt $maxNo) { $maxNo = $n }
  }
}

$nextNo = $maxNo + 1
$prefix = "{0:D3}" -f $nextNo
$fileName = "${prefix}_daily_${Date}_${topic}.sql"
$fullPath = Join-Path $seedDir $fileName

if (Test-Path $fullPath) {
  throw "File already exists: $fullPath"
}

$template = @"
-- [PromptSkiller] Daily batch seed ($Date)
-- Generated by scripts/new-daily-seed.ps1
-- Naming: NNN_daily_YYYYMMDD_<topic>.sql

-- 1) drills upsert
-- insert into public.drills (id, display_no, title, body_md, difficulty, tags, drill_type, published_at)
-- values (...)
-- on conflict (id) do update set ...;

-- 2) drill_assets upsert (optional for code_case_multi/build_sim_case)
-- insert into public.drill_assets (drill_id, asset_kind, path, content_text, order_no)
-- values (...)
-- on conflict (drill_id, asset_kind, path) do update set ...;

-- 3) drill_template_rounds upsert (optional for template_case)
-- insert into public.drill_template_rounds (drill_id, round_no, version_label, prompt_text, teaching_notes_md)
-- values (...)
-- on conflict (drill_id, round_no) do update set ...;

-- 4) drill_schedule upsert (optional)
-- insert into public.drill_schedule (date, slot, drill_id)
-- values ('YYYY-MM-DD', 1, 'drill-id')
-- on conflict (date, slot) do update set drill_id = excluded.drill_id;
"@

# Write without BOM for cross-version PowerShell compatibility.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($fullPath, $template, $utf8NoBom)
Write-Host "Created $fullPath"
